name: Playwright Tests

on:
  pull_request:
    branches:
      - "**"
  # push:
    # branches:
      # - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - name: List CWD
        run: ls test-results/

      - name: Upload Playwright results
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: test-results/

      - name: Generate and post Playwright report summary
        uses: daun/playwright-report-summary@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          report-file: results.json

      - name: Upload Playwright report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Comment on pull request
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\": \"Playwright test results: $TEST_RESULTS_SUMMARY\"}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_RESULTS_SUMMARY: $(cat summary.json)
