name: Visual Review Deployment

on:
  push:
    branches:
      - "**"
      - "!main"

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  wait_for_deployement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prompt/actions-commit-hash@v3
        id: push-changes
      - name: install dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@18.9.0
        with:
          args: install
        env:
          CI: "true"
      - name: Await CF Pages
        id: cfDeploy
        uses: WalshyDev/cf-pages-await@v1.3.1
        with:
          apiKey: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          accountEmail: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          project: "ascentiaci-ca"
          commitHash: ${{ steps.push-changes.outputs.hash }}
      - name: Take Screenshots
        id: screenshots
        uses: xxidbr9/screenshots-action@v1.1.18
        with:
          url: ${{ steps.cfDeploy.outputs.url }}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          path: screenshots
          name: Download-screenshots
      - name: Comment on pull request
        uses: live-codes/pr-comment-from-artifact@v1.0.1
